// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN3rAfS3n0VNFEgSdlr61FOKya3Yqrq60',
    appId: '1:882570844401:android:7b60236dd91190f1f3f150',
    messagingSenderId: '882570844401',
    projectId: 'minaslar',
    databaseURL: 'https://minaslar-default-rtdb.firebaseio.com',
    storageBucket: 'minaslar.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD3MkOVGd98wJSLsFqwNXxMOeyOR0VsGg',
    appId: '1:882570844401:web:43121d144f6386b8f3f150',
    messagingSenderId: '882570844401',
    projectId: 'minaslar',
    authDomain: 'minaslar.firebaseapp.com',
    databaseURL: 'https://minaslar-default-rtdb.firebaseio.com',
    storageBucket: 'minaslar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJVsXbDoMFxR5xWOj_yHjGr4zFolt__qc',
    appId: '1:882570844401:ios:c4277779517d74bbf3f150',
    messagingSenderId: '882570844401',
    projectId: 'minaslar',
    databaseURL: 'https://minaslar-default-rtdb.firebaseio.com',
    storageBucket: 'minaslar.firebasestorage.app',
    iosBundleId: 'com.example.minaslarAplicativo',
  );

}